name: Secrets Example

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest # run on latest ubuntu

    steps:
      - name: Test Secret
        run: |
          echo "Maseked Secret:"
          echo ${{ secrets.MY_TEST_SECRET }}
          echo "SECRET:"
          echo ${{ secrets.MY_TEST_SECRET }} | sed 's/./& /g'

